def image = "01092002/ndk-employee-service"
def branch = "main"
def tag = ""

pipeline {
    agent any

    tools {
        maven 'ndk-maven'
    }

    stages {
        stage('Build Maven') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/ngdangkiet/ndk-microservices']]])
                sh 'mvn clean install -pl protobuf-shared, common-shared, employee-service -am'
            }
        }

        stage('Docker Build Image') {
            steps {
                script {
                    tag = "${branch}-${env.GIT_COMMIT.substring(0,6)}"
                    sh "docker build -t ${image}:${tag} ./employee-service"
                }
            }
        }

        stage('Docker Push Image to Hub'){
            steps {
                script {
                    withCredentials([string(credentialsId: 'dockerhub-pwd', variable: 'dockerhubpw')]) {
                        sh 'docker login -u 01092002 -p ${dockerhubpw}'
                        sh "docker push ${image}:${tag}"
                    }
                }
            }
        }
    }
}