def image = "01092002/ndk-config-server"
def branch = "main"
def tag = ""

pipeline {
    agent any

    tools {
        maven 'ndk-maven'
    }

    stages {
        stage('Build Maven') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/ngdangkiet/ndk-microservices']]])
                sh 'mvn clean install -pl config-server -am'
            }
        }

        stage('Docker Build and Push'){
            steps {
                script {
                    withDockerRegistry(credentialsId: 'dockerhub', url: 'https://index.docker.io/v1/') {
                        tag = "${branch}-${env.GIT_COMMIT.substring(0,6)}"
                        sh "docker build -t ${image}:${tag} ."
                        sh "docker push ${image}:${tag}"
                    }
                }
            }
        }
    }
}